spring:
  datasource:
    url: jdbc:mysql://localhost:3306/?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver