spring:
  datasource:
    url: jdbc:mysql://localhost:3306/?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: "2"
    password: "2"
    driver-class-name: com.mysql.cj.jdbc.Driver