server:
#  tomcat:
#    threads:
#      max: 250

  servlet:
    session:
      cookie:
        same-site: None
        secure: true

    encoding:
      charset: UTF-8
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: username
    url: url
    password: pw
#    hikari:
#      maximum-pool-size: 250

  mail:
    host: smtp.naver.com
    port: 465
    username: username
    password: password
    properties:
      debug: true
      mail:
        stmp:
          auth : true
          starttls :
            enable: true
          ssl :
            enable : true
            trust : smtp.naver.com

  redis:
    host: localhost
    port: 6379
#    redisson_bid_lock: bidLock
    redisson_bid_lock0: bidLock0
    redisson_bid_lock1: bidLock1
    redisson_bid_lock2: bidLock2

  profiles:
    include:
      - sec
    active: local

  jpa:
    hibernate:
#      ddl-auto: none
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
    open-in-view: false

  messages:
    basename: errors

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
# AWS S3
cloud:
  aws:
    credentials:
      access-key: "access-key"
      secret-key: "secret-key"

    region:
      static: "region-name"
    stack:
      auto: false

    s3:
      bucket: "bucket-name"

jwt:
  header: Authorization
  secret: x
  access-token-validity-in-seconds: 1728000 # 20 days
  refresh-token-validity-in-seconds: 1800 # 30 min

springdoc:
  packages-to-scan: com.auction.usedauction.web.controller
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    doc-expansion: none

OPENVIDU_URL: url
OPENVIDU_SECRET: url

INIT_FILE_PATH: src/main/resources/files/

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace