server:
  servlet:
    session:
      cookie:
        same-site: None
        secure: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: username
    url: url
    password: pw

  profiles:
    include:
      - sec
    active: local

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
    open-in-view: false

  messages:
    basename: errors

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

# AWS S3
cloud:
  aws:
    credentials:
      access-key: "access-key"
      secret-key: "secret-key"

    region:
      static: "region-name"
    stack:
      auto: false

    s3:
      bucket: "bucket-name"
